apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fchost
  region: us-east-1

vpc:
  id: 'vpc-0cb195bf93b2f0bb1'
  subnets:
    public:
      us-east-1a:
        id: 'subnet-00da8cfbb0694e349'
      us-east-1b:
        id: 'subnet-064c03e80b04ba20d'
      us-east-1c:
        id: 'subnet-095938fe3c11f984d'
      us-east-1d:
        id: 'subnet-022af9b2f4f91c9f7'

nodeGroups:
  - name: fchost-api-ng
    instanceType: t3a.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    ssh:
      allow: true
      publicKeyName: fchost
