apiVersion: apps/v1
kind: Deployment
metadata:
  name: fchost-deployment
  # namespace: fchost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fchost-api
  template:
    metadata:
      labels:
        app: fchost-api
    spec:
      containers:
        - name: fchost-api
          image: public.ecr.aws/e0j5c6t0/fchost/api:latest
          resources:
            limits:
              memory: '512Mi'
              cpu: '500m'
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              value: 'api'
            - name: NODE_ENV
              value: 'dev'

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: fchost-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: fchost-config
                  key: DB_PORT

            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: fchost-config
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: fchost-config
                  key: DB_PASSWORD

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: fchost-config
                  key: DB_NAME

            - name: RABBITMQ_URI
              valueFrom:
                configMapKeyRef:
                  name: fchost-config
                  key: RABBITMQ_URI
---
apiVersion: v1
kind: Service
metadata:
  name: fchost-service
  # namespace: fchost
spec:
  type: NodePort
  selector:
    app: fchost-api
  ports:
    - protocol: TCP
      port: 8080
      # targetPort: 8080
