apiVersion: apps/v1
kind: Deployment
metadata:
  name: fchost-deployment
  # namespace: fchost
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fchost-api
  template:
    metadata:
      labels:
        app: fchost-api
    spec:
      containers:
        - name: fchost-api
          image: 319780005892.dkr.ecr.us-east-1.amazonaws.com/fchost-api:latest
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fchost-service
  # namespace: fchost
spec:
  type: LoadBalancer
  selector:
    app: fchost-api
  ports:
    - port: 8081
      targetPort: 80
