services:
  fchost-api:
    container_name: fchost-api
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    restart: always

    ports:
      - 8080:80 # porta default da api
      - 8081:8081 # porta do debugger

    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app/apps/api/src

    environment:
      - APP_NAME=api
      - NODE_ENV=dev
      - DB_HOST=fchost-postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=fchost
      # - RABBITMQ_URI=amqp://rabbitmq:rabbitmq@fchost-rabbitmq:5672
      - RABBITMQ_URI=amqps://xxinxjrt:700e4XYDwyOF6-y4IibOBw8U2ytGAYqn@moose.rmq.cloudamqp.com/xxinxjrt

    # develop:
    #   watch:
    #     - path: .
    #       action: sync+restart
    #       target: /usr/src/app/apps/api
    # exec:
    #   command: npm run start:prod:api

    command: npm run start:debug:api

    networks:
      - kind

# kind k8s
networks:
  kind: # ficar ligado no nome
    external: true
# networks:
#   fchost_network: # ficar ligado no nome
#     external: true
