services:
  fcpay-api:
    container_name: fcpay-api
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    restart: always

    ports:
      - 8080:8080 # porta default da api
      - 8081:8081 # porta  do debugger

    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app/apps/api/src

    environment:
      - APP_NAME=api
      - NODE_ENV=dev
      - DB_HOST=fcpay-postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=fcpay

    # develop:
    #   watch:
    #     - path: .
    #       action: sync+restart
    #       target: /usr/src/app/apps/api
    # exec:
    #   command: npm run start:prod:api

    networks:
      - fcpay_network

networks:
  fcpay_network: # ficar ligado no nome
    external: true
