services:
  fchost-api:
    container_name: fchost-api
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    restart: always

    ports:
      - 8080:8080 # porta default da api
      - 8081:8081 # porta do debugger

    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app/apps/api/src

    environment:
      - APP_NAME=api
      - NODE_ENV=dev
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - RABBITMQ_URI=${RABBITMQ_URI}
      - AWS_SES_USER_ACCESS_KEY=${AWS_SES_USER_ACCESS_KEY}
      - AWS_SES_USER_SECRET_ACCESS_KEY=${AWS_SES_USER_SECRET_ACCESS_KEY}

    command: npm run start:debug:api

    networks:
      # - kind
      - fchost_network

# kind k8s
networks:
  # kind: # ficar ligado no nome
  #   external: true
  fchost_network: # ficar ligado no nome
    external: true
